/**
 * @file orxExtensions.h
 * !! This file is automatically generated by init, do not modify manually. !!
 * @date 27-Aug-2025
 */

#ifndef _orxEXTENSIONS_H_
#define _orxEXTENSIONS_H_

#define orxNOISETEXTURE_IMPL
#include "orxNoiseTexture.h"
#undef orxNOISETEXTURE_IMPL

#define orxIMGUI_IMPL
#include "orxImGui.h"
#undef orxIMGUI_IMPL

#define orxINSPECTOR_IMPL
#include "orxInspector.h"
#undef orxINSPECTOR_IMPL

#define orxCONTAINER_IMPL
#include "container/orxContainer.h"
#undef orxCONTAINER_IMPL

#define orxBUNDLE_IMPL
#include "orxBundle.h"
#undef orxBUNDLE_IMPL

void InitExtensions()
{
  // Initialize noise texture support
  orxNoiseTexture_Init();

  // Initialize Dear ImGui
  orxImGui_Init();

  // Initialize inspector
  orxInspector_Init();

  // Initialize container
  orxContainer_Init();
}

void ExitExtensions()
{
  // Exit from inspector
  orxInspector_Exit();

  // Exit from Dear ImGui
  orxImGui_Exit();

  // Exit from noise texture support
  orxNoiseTexture_Exit();

  // Exit from bundle support
  orxBundle_Exit();

  // Exit from container
  orxContainer_Exit();
}

void BootstrapExtensions()
{
  // Initialize bundle resource type
  orxBundle_Init();

  // Add config storage to find the initial config file
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, orxBUNDLE_KZ_RESOURCE_STORAGE, orxFALSE);
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, orxBUNDLE_KZ_RESOURCE_STORAGE "olcjam2025.obr", orxFALSE);
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, "../data/config", orxFALSE);
}

#endif // _orxEXTENSIONS_H_
